dubbo:
  protocol:
    name: dubbo
    port: 12345
    payload: 8388608
  registry:
    address: N/A
  scan:
    base-packages: demo.provider.api
  provider:
    timeout: 30000
server:
  port: 8080
logging:
  root: debug
spring:
  application:
    name: server